### ISSUE TITLE
Unrecognized options "decimal_part" under "lexik_currency".

### ISSUE THREAD

**Issue by OrangeTux** [lexik/LexikCurrencyBundle#16]
When I use the config from the example:

``` yaml
  # app/config/config.yml
  lexik_currency:
      decimal_part:
          precision:  2                           # number of digits for the decimal part
          round_mode: up                          # round mode to use (up|down|even|odd)
```

I get an an error:

``` php
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "decimal_part" under "lexik_currency"   
```

I've checked the source and I could not find a clue why it does not work.
