### ISSUE TITLE
Custom adapter example not working !

### ISSUE THREAD

**Issue by maxvanceffer** [lexik/LexikCurrencyBundle#46]
Using example for custom provider, is not working:

Symfony 2.7 
Lexik bundle 2.0

```yml
# config.yml 
lexik_currency:
    default_adapter: mcb_currency_adapter
    currencies:
        default: MDL              # [required] the default currency
        managed: [EUR, RON, USD]  # [required] all currencies used in your app
```
```yml
# services.yml 
services: 
    mcb_currency_adapter:
        class:  MG\TrackBundle\Extensions\McbCurrencyAdapter
        tags:
            - { name: lexik_currency.adapter, alias: mcb_currency_adapter }
```
 class 
```php
class McbCurrencyAdapter extends AbstractCurrencyAdapter
{
    /**
     * {@inheritdoc}
     */
    public function attachAll()
    {
       ....
    }

    /**
     * {@inheritdoc}
     */
    public function getIdentifier()
    {
        return 'mcb';
    }
}
```

And when i call

    ./app/console lexik:currency:import mcb

I get this error:
```
 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "lexik_currency.converter" has a dependency on a non-existent service "lexik_currency.default_adapter".
```

Also when i remove from config this row:   default_adapter: mcb_currency_adapter

And when i call

    ./app/console lexik:currency:import mcb

I get this error:
```
PHP Fatal error:  Class name must be a valid object or a string in vendor/lexik/currency-bundle/Adapter/AbstractCurrencyAdapter.php on line 85
```

**Comment by cedric-g** [comment]
Hi, 

About the first error by defining the `default_adapter` option, this https://github.com/lexik/LexikCurrencyBundle/commit/745b6dc77ad5078284dcd91f5cc69f746d8c4c00 should fix it, but `master` branch require SF2.8.

About the second error, I think we forgot something in the doc, can you try by adding the `calls` section in your service definition ?
```yml
services: 
    mcb_currency_adapter:
        class:  MG\TrackBundle\Extensions\McbCurrencyAdapter
        calls:
            - [ setDefaultCurrency, [ %lexik_currency.currencies.default% ] ]
            - [ setManagedCurrencies, [ %lexik_currency.currencies.managed% ] ]
            - [ setCurrencyClass, [ %lexik_currency.currency_class% ] ]
        tags:
            - { name: lexik_currency.adapter, alias: mcb_currency_adapter }
```
