### ISSUE TITLE
lexik:currency:import yahoo not working

### ISSUE THREAD

**Issue by medevphp** [lexik/LexikCurrencyBundle#54]
lexik:currency:import yahoo not working
Seems like yahoo has discontinued the service.

Digging deeper, found the following response from their API : 

> It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by jdambacher** [comment]
You're right! I will search for another service providing worldwide currency exchanges.

**Comment by jdambacher** [comment]
I've created an adapter for AlphaVantage. It's a free API supporting a lot of currencies, so it's a perfect replacement for the Yahoo adapter. See #55

**Comment by jdambacher** [comment]
I think after merging my pull request, this issue can be closed. @All Yahoo adapter users: Please use the new AlphaVantage adapter instead.

**Comment by devHanane** [comment]
Hello, 

Can u please share with us the adapter that you have created. I'm newbie to symfony and I'm using this bundle because my website is multi-currency site. I tried to use ECB but it doesn't contain "MAD" currency of my country. I have created the account in alphavantage but didn"t know where to add code to create custom provider( I have seen the example provided in the doc but I don"t know how to implement it)

**Comment by jdambacher** [comment]
@devHanane
Unfortunately, my PR is still not merged, but you can check out my fork: https://github.com/coffee-bike/LexikCurrencyBundle

It's fully working with the AlphaAdvantage Adapter

**Comment by jdambacher** [comment]
You just have to add the following to your `config.yml`:

```
lexik_currency:  
    currencies:
        default: EUR
        managed: [EUR, CHF, CZK, KWD, RON, GBP, QAR, INR, AED, PLN, TRY, SAR, MKD, HUF]  
    default_adapter: alpha_currency_adapter
    alpha_api_key: '<YOUR API KEY>'
```
